baseURL: "https://zorartic.github.io/portfolio/" 
title: Zaurayz Kashan Shah
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Thesis
          url: thesis/
          weight: 2
        - name: Research Projects
          url: projects/
          weight: 3

params:
    description: "This website hosts Zaurayz K. Shah's thesis, research projects, curriculum vitae, and contact information."
    author: Zaurayz K. Shah
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["thesis","projects","contact"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Zaurayz Kashan Shah
          subtitle: "I am a physics graduate from NUST. My research focuses on theoretical high-energy physics with interests in particle physics, automotive engineering, and good coffee."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Thesis
              url: thesis/
            - name: Research Projects
              url: projects/
            - name: Contact
              url: contact/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:zaurayzs15@gmail.com
        - name: linkedin
          url: https://www.linkedin.com/in/zaurayz-kashan-shah-43232a350/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Zaurayz K. Shah"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
